# Character Locks Extension Configuration
# This file controls extension behavior in both single-user and multi-user environments.

# =============================================================================
# MULTI-USER ACCESS CONTROLS
# =============================================================================

# Allow non-admin users to have full access to all extension features
# When true: Non-admin users can use all features
# When false: Non-admin users are restricted by the settings below
# Default: false
allowNonAdminFullAccess: false

# Allow non-admin users to edit Boolean filter expressions
# When true: Non-admin users can create/edit/delete model-prompt filter rules
# When false: Non-admin users have read-only access to filter configurations
# Note: This setting is ignored if allowNonAdminFullAccess is true
# Default: false
allowNonAdminEditFilters: false

# Allow non-admin users to enable/disable model-prompt linkage
# When true: Non-admin users can toggle the Model-Prompt Links feature on/off
# When false: Non-admin users cannot modify the Model-Prompt Links setting
# Note: This setting is ignored if allowNonAdminFullAccess is true
# Default: false
allowNonAdminToggleModelPrompt: false

# =============================================================================
# MASTER SOURCE CONFIGURATION
# =============================================================================

# URL or file path for importing prompt templates in JSON format
# When configured:
#   - Automatically imports/overrides templates on extension load
#   - Disables template editing UI with warning message
#   - Enables centralized template management
# Examples:
#   - "https://example.com/templates.json"
#   - "file:///path/to/templates.json"
#   - "" (empty string disables master source)
# Default: "" (disabled)
promptTemplateImportSource: ""

# URL or file path for importing Boolean filter configurations in JSON format
# When configured:
#   - Automatically imports/overrides filter rules on extension load
#   - Disables filter editing UI with warning message
#   - Enables centralized filter rule management
# Examples:
#   - "https://example.com/filters.json"
#   - "file:///path/to/filters.json"
#   - "" (empty string disables master source)
# Default: "" (disabled)
booleanFiltersSource: ""

# =============================================================================
# IMPLEMENTATION NOTES
# =============================================================================

# 1. Single-User Mode:
#    - All access restrictions are automatically bypassed
#    - User is always considered admin
#    - Master source settings still apply

# 2. Multi-User Mode:
#    - Settings are stored per user handle
#    - Admin users always have full access regardless of these settings
#    - Non-admin users are restricted based on configuration above

# 3. Configuration Priority:
#    - This config.yaml file provides default values
#    - SillyTavern extension settings can override these defaults
#    - Admin users can always modify settings regardless of restrictions

# 4. Master Source Behavior:
#    - When master sources are configured, manual imports are disabled
#    - Export functionality remains available for reference
#    - Sources are refreshed periodically (5-minute minimum interval)
#    - Failed loads fall back to existing configurations